/** ISO 3166-1 alpha-2 codes for country name to flag emoji conversion. */
export const COUNTRY_CODES: Record<string, string> = {
  // North Africa & Middle East
  Tunisia: 'TN',
  Morocco: 'MA',
  Algeria: 'DZ',
  Egypt: 'EG',
  Libya: 'LY',
  Sudan: 'SD',
  UAE: 'AE',
  'Saudi Arabia': 'SA',
  Qatar: 'QA',
  Kuwait: 'KW',
  Bahrain: 'BH',
  Oman: 'OM',
  Yemen: 'YE',
  Jordan: 'JO',
  Lebanon: 'LB',
  Syria: 'SY',
  Iraq: 'IQ',
  Palestine: 'PS',
  Iran: 'IR',
  Turkey: 'TR',

  // Europe
  France: 'FR',
  Germany: 'DE',
  UK: 'GB',
  'United Kingdom': 'GB',
  Spain: 'ES',
  Italy: 'IT',
  Portugal: 'PT',
  Netherlands: 'NL',
  Belgium: 'BE',
  Switzerland: 'CH',
  Austria: 'AT',
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
  Finland: 'FI',
  Ireland: 'IE',
  Poland: 'PL',
  'Czech Republic': 'CZ',
  Czechia: 'CZ',
  Romania: 'RO',
  Greece: 'GR',
  Hungary: 'HU',
  Croatia: 'HR',
  Bulgaria: 'BG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Lithuania: 'LT',
  Latvia: 'LV',
  Estonia: 'EE',
  Luxembourg: 'LU',
  Malta: 'MT',
  Iceland: 'IS',
  Serbia: 'RS',
  Ukraine: 'UA',
  Russia: 'RU',
  Belarus: 'BY',
  Moldova: 'MD',
  Albania: 'AL',
  'North Macedonia': 'MK',
  Montenegro: 'ME',
  'Bosnia and Herzegovina': 'BA',
  Kosovo: 'XK',
  Cyprus: 'CY',
  Monaco: 'MC',
  Liechtenstein: 'LI',
  Andorra: 'AD',
  'San Marino': 'SM',
  'Vatican City': 'VA',
  Georgia: 'GE',
  Armenia: 'AM',
  Azerbaijan: 'AZ',

  // Americas
  USA: 'US',
  'United States': 'US',
  Canada: 'CA',
  Mexico: 'MX',
  Brazil: 'BR',
  Argentina: 'AR',
  Chile: 'CL',
  Colombia: 'CO',
  Peru: 'PE',
  Venezuela: 'VE',
  Ecuador: 'EC',
  Bolivia: 'BO',
  Paraguay: 'PY',
  Uruguay: 'UY',
  Guyana: 'GY',
  Suriname: 'SR',
  Panama: 'PA',
  'Costa Rica': 'CR',
  Nicaragua: 'NI',
  Honduras: 'HN',
  'El Salvador': 'SV',
  Guatemala: 'GT',
  Belize: 'BZ',
  Cuba: 'CU',
  Jamaica: 'JM',
  Haiti: 'HT',
  'Dominican Republic': 'DO',
  'Trinidad and Tobago': 'TT',
  Bahamas: 'BS',
  Barbados: 'BB',

  // Asia
  China: 'CN',
  Japan: 'JP',
  'South Korea': 'KR',
  'North Korea': 'KP',
  India: 'IN',
  Pakistan: 'PK',
  Afghanistan: 'AF',
  Singapore: 'SG',
  Malaysia: 'MY',
  Indonesia: 'ID',
  Thailand: 'TH',
  Vietnam: 'VN',
  Philippines: 'PH',
  Taiwan: 'TW',
  'Hong Kong': 'HK',
  Macau: 'MO',
  Bangladesh: 'BD',
  'Sri Lanka': 'LK',
  Nepal: 'NP',
  Bhutan: 'BT',
  Myanmar: 'MM',
  Cambodia: 'KH',
  Laos: 'LA',
  Mongolia: 'MN',
  Kazakhstan: 'KZ',
  Uzbekistan: 'UZ',
  Turkmenistan: 'TM',
  Tajikistan: 'TJ',
  Kyrgyzstan: 'KG',
  Maldives: 'MV',
  Brunei: 'BN',
  'Timor-Leste': 'TL',

  // Oceania
  Australia: 'AU',
  'New Zealand': 'NZ',
  Fiji: 'FJ',
  'Papua New Guinea': 'PG',
  Samoa: 'WS',
  Tonga: 'TO',
  Vanuatu: 'VU',

  // Sub-Saharan Africa
  'South Africa': 'ZA',
  Nigeria: 'NG',
  Kenya: 'KE',
  Ghana: 'GH',
  Ethiopia: 'ET',
  Tanzania: 'TZ',
  Senegal: 'SN',
  'Ivory Coast': 'CI',
  "Cote d'Ivoire": 'CI',
  Uganda: 'UG',
  Cameroon: 'CM',
  Zimbabwe: 'ZW',
  Zambia: 'ZM',
  Mozambique: 'MZ',
  Angola: 'AO',
  Botswana: 'BW',
  Namibia: 'NA',
  Mali: 'ML',
  Niger: 'NE',
  Chad: 'TD',
  'Burkina Faso': 'BF',
  Guinea: 'GN',
  Benin: 'BJ',
  Togo: 'TG',
  Rwanda: 'RW',
  Burundi: 'BI',
  Somalia: 'SO',
  Eritrea: 'ER',
  Djibouti: 'DJ',
  'South Sudan': 'SS',
  Malawi: 'MW',
  Madagascar: 'MG',
  Mauritius: 'MU',
  Gabon: 'GA',
  'Congo (DRC)': 'CD',
  'Democratic Republic of the Congo': 'CD',
  Congo: 'CG',
  'Republic of the Congo': 'CG',
  Liberia: 'LR',
  'Sierra Leone': 'SL',
  'Equatorial Guinea': 'GQ',
  Gambia: 'GM',
  'Guinea-Bissau': 'GW',
  Lesotho: 'LS',
  Eswatini: 'SZ',
  Mauritania: 'MR',
  'Cabo Verde': 'CV',
  Comoros: 'KM',
  Seychelles: 'SC',
  'Central African Republic': 'CF',
};

export const NORMALIZED_COUNTRY_CODES: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_CODES).map(([country, code]) => [country.toLowerCase(), code]),
);
