/**
 * Reads `.env` / process env and writes OAuth client IDs into generated
 * build inputs. Chrome cannot read `.env` at runtime — this is build-time only.
 *
 * Required for `npm run package` (store ZIP). Optional for CI / unit tests:
 * missing values become empty strings and Google sign-in will not work.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const requireIds = process.argv.includes('--require');

const CHROME_KEY = 'CANDIDEX_CHROME_OAUTH_CLIENT_ID';
const WEB_FLOW_KEY = 'CANDIDEX_WEB_FLOW_OAUTH_CLIENT_ID';
const CLIENT_ID_RE = /^[0-9]+-[a-z0-9]+\.apps\.googleusercontent\.com$/i;

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const text = fs.readFileSync(filePath, 'utf8');
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

function isValidClientId(value) {
  return typeof value === 'string' && CLIENT_ID_RE.test(value.trim());
}

loadEnvFile(path.join(root, '.env'));

const chromeId = (process.env[CHROME_KEY] || '').trim();
const webFlowId = (process.env[WEB_FLOW_KEY] || '').trim();

if (requireIds) {
  const missing = [];
  if (!isValidClientId(chromeId)) missing.push(CHROME_KEY);
  if (!isValidClientId(webFlowId)) missing.push(WEB_FLOW_KEY);
  if (missing.length > 0) {
    console.error('Missing or invalid OAuth client IDs for the store ZIP.');
    console.error(`Copy .env.example to .env and set:\n  ${missing.join('\n  ')}`);
    process.exit(1);
  }
} else if (!chromeId || !webFlowId) {
  console.warn(
    'OAuth client IDs not set. Google sign-in will fail until you copy .env.example to .env.'
  );
}

const generatedDir = path.join(root, '.generated');
fs.mkdirSync(generatedDir, { recursive: true });

const sourceManifestPath = path.join(root, 'src', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(sourceManifestPath, 'utf8'));
manifest.oauth2 = manifest.oauth2 || {};
manifest.oauth2.client_id = chromeId;
fs.writeFileSync(
  path.join(generatedDir, 'manifest.json'),
  `${JSON.stringify(manifest, null, 2)}\n`
);

fs.writeFileSync(
  path.join(generatedDir, 'oauth-clients.json'),
  `${JSON.stringify({ chrome: chromeId, webFlow: webFlowId }, null, 2)}\n`
);

const configDir = path.join(root, 'src', 'app', 'core', 'config');
fs.mkdirSync(configDir, { recursive: true });
fs.writeFileSync(
  path.join(configDir, 'oauth-clients.generated.ts'),
  `// Generated by scripts/prepare-oauth.mjs — do not edit or commit.
export const CANDIDEX_WEB_FLOW_OAUTH_CLIENT_ID = ${JSON.stringify(webFlowId)};
`
);

if (chromeId || webFlowId) {
  console.log('OAuth client IDs written for this build.');
}